### ISSUE TITLE
Where can I get this map?

### ISSUE THREAD

**Issue by yellowflash2041** [MetalfOxXer/Naruto_Ninpou#227]
I think this map is amazing and looks fun.
Could you tell me where I can get it?

**Comment by MetalfOxXer** [comment]
> 

join the discord channel: https://discord.gg/8SSUVEP

**Comment by MetalfOxXer** [comment]
this is a custom game for Warcraft III Reforged, if you want to play it you have to download the map and install Warcraft III Reforged, here is the latest version: https://drive.google.com/file/d/15yv7MLQkUJNNddnHF8ZXY-fiBHd9gTTK/view?usp=sharing

**Comment by yellowflash2041** [comment]
Thanks. You are awesome. I will close this issue.
